### ISSUE TITLE
[Help wanted] Access the database from a Symfony API project

### ISSUE THREAD

**Issue by thejoelinux** [thephpleague/oauth2-server-bundle#101]
I try to write a web interface to create, activate (and so on) clients, but when I try to map my entities on the tables, I can't read the datas because conversion failed. Errors are like :
`Could not convert database value "https://some-redirect-uri..." to Doctrine Type json`
Doctrine seems to think the values are in json - this is not the case.

I saw in the database comments on fields like `(DC2Type:oauth2_redirect_uri)` and some others, but I did not find a way to use the `types` I saw in the configuration like :
```yaml
  types:
      oauth2_grant:
          class: League\Bundle\OAuth2ServerBundle\DBAL\Type\Grant
      oauth2_redirect_uri:
          class: League\Bundle\OAuth2ServerBundle\DBAL\Type\RedirectUri
      oauth2_scope:
          class: League\Bundle\OAuth2ServerBundle\DBAL\Type\Scope
```
I think some annotations are needed in my entities, and then some way to convert a space-delimited value to an array back and forth.

Thanks in advance for any help on this subject.
