### ISSUE TITLE
Overriding the default endpoints path

### ISSUE THREAD

**Issue by Methraen** [thephpleague/oauth2-server-bundle#102]
It would be really helpful to be able to override/configure the default path for the endpoints, like going from :
```
app.oauth2:
    host: "%api_host%"
    resource: '@LeagueOAuth2ServerBundle/Resources/config/routes.php'
    type: php
```
to :
```
app.oauth2_token:
    host: "%api_host%"
    path: /oauth/v2/token
    methods: POST
    controller: League\Bundle\OAuth2ServerBundle\Controller\TokenController::indexAction
```

This example does not currently work as the TokenController is not public (The controller for URI \"/oauth/v2/token\" is not callable: Controller \"League\\Bundle\\OAuth2ServerBundle\\Controller\\TokenController\" cannot be fetched from the container because it is private. Did you forget to tag the service with \"controller.service_arguments\"?).

**Comment by etshy** [comment]
Here is the config `services.php` from the bundle
```
$container->services()
...
 ->set('league.oauth2_server.controller.token', TokenController::class)
            ->args([
                service(AuthorizationServer::class),
                service('league.oauth2_server.factory.psr_http'),
                service('league.oauth2_server.factory.http_foundation'),
                service('league.oauth2_server.factory.psr17'),
                service('event_dispatcher'),
            ])
            ->tag('controller.service_arguments')
        ->alias(TokenController::class, 'league.oauth2_server.controller.token')
```
If I remember right, it's private by default.
Maybe you can try using the alias in your route overide ? Or try to re-define the Controler in your service (and set it to public ?) ?
Not sure if that could work though, I found this issue while searching doc/issue for the same question but didn't try anything yet.

**Comment by Methraen** [comment]
Well seen @etshy using the alias works !

```
api_oauth2_token:
    host: "%api_host%"
    path: /oauth/v2/token
    methods: POST
    controller: 'league.oauth2_server.controller.token::indexAction'
```
