### ISSUE TITLE
Error associated with NullUser class

### ISSUE THREAD

**Issue by facundososalopez** [thephpleague/oauth2-server-bundle#134]
I don't know why this error occurs:

"The class 'League\\Bundle\\OAuth2ServerBundle\\Security\\User\\NullUser' was not found in the chain configured namespaces App\\Entity\\Main, League\\Bundle\\OAuth2ServerBundle\\Entity, League\\Bundle\\OAuth2ServerBundle\\Model"

symfony 6.2
doctrine-bundle 2.8.3

here's my doctrine orm configuration:

```yaml
doctrine:
    ...
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true                    
        entity_managers:
            default:        
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                dql:
                    datetime_functions:
                        YEAR: DoctrineExtensions\Query\Mysql\Year
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        DAY: DoctrineExtensions\Query\Mysql\Day
            auditoria:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: auditoria
                mappings:
                    Auditoria:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Auditoria'
                        prefix: 'App\Entity\Auditoria'
                        alias: Auditoria

```

and here's my league_oauth2_server configation:

```yaml

league_oauth2_server:
  ...
  persistence:
    doctrine:
      entity_manager: default

```

The error occurs when the flush method is executed, and only on a specific endpoint.
