### ISSUE TITLE
Multiple User Providers

### ISSUE THREAD

**Issue by dernst-art** [thephpleague/oauth2-server-bundle#41]
If I create multiple user providers I always get the following error:
```
The service "security.authenticator.oauth2.api" has a dependency on a non-existent service "Symfony\Component\Security\Core\User\UserProviderInterface".
```
Even if I explicitly set the user provider in the firewall config:
```
[...]
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
        app_user_provider2:
[...]
    firewalls:                
        api:
            pattern: ^/api
            security: true
            stateless: true
            provider: app_user_provider
            oauth2: true
[...]
```
Argument binding is not working also.
Is it possible to configure the user provider of the authenticator or am I missing something?
