### ISSUE TITLE
Symfony 6.1 oauth2 option doesn't work

### ISSUE THREAD

**Issue by gutig** [thephpleague/oauth2-server-bundle#94]
Hi I'm using symfony 6.1 and the firewall for oauth2 doesn't seem to be doing anything. So for example I have this setup in secruity.yaml;

```
firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_token:
            pattern: ^/api/token$
            security: false
        api:
            pattern: ^/rest
            security: true
            stateless: true
            oauth2: true // <--- doesn't seem to ask for auth
        main:
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
            lazy: true
            switch_user: { role: CAN_SWITCH_USER }
            provider: app_user_provider
            login_throttling:
                max_attempts: 10
                interval: '10 minutes'
            custom_authenticator:
                - App\Security\LoginFormAuthenticator
            user_checker: App\Security\UserChecker
            logout:
                path: dashboard_logout
                target: dashboard_login
```

and then I have an api controller as follows;

```
<?php

namespace App\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/rest')]
class RestController extends AbstractController
{

    #[Route('', name: 'rest_index', defaults: ["oauth2_scopes"=>["EMAIL", "PREFERENCES"]])]
    public function index(): Response
    {
        return new JsonResponse(['data'=>['a', 'b', 'c']]);
    }

}

```

When making a request to this endpoint I can do this without passing a bearer token. And the docs say `Basically, any firewall which sets the oauth2 parameter to true will make any routes that match the selected pattern go through our OAuth 2.0 security layer.` (https://github.com/thephpleague/oauth2-server-bundle/blob/master/docs/basic-setup.md) Has this stopped working on Symfony 6.1?
